version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - STEAM_API_KEY=${STEAM_API_KEY}
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite:/app/db.sqlite
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:3000
    depends_on:
      - backend
